- name: Create ECS Task Execution Role
  amazon.aws.iam_role:
    name: ecsTaskExecutionRole
    assume_role_policy_document:
        Version: "2012-10-17"
        Statement:
          -  Effect: "Allow"
             Principal:
              Service: ecs-tasks.amazonaws.com
             Action: sts:AssumeRole
    state: present
  register: ecs_execution_role