name: Deploy AWS Infra with Ansible (OIDC + Secrets)

on:
  push:

permissions:
  id-token: write   # REQUIRED for AWS OIDC
  contents: read

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # --------------------------------------------------
      # Checkout code
      # --------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------------------------------
      # Assume AWS IAM Role via OIDC (NO secrets)
      # Stored rolearn in Github environment
      # -----------------------------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      # --------------------------------------------------
      # (Optional but recommended) Verify identity
      # --------------------------------------------------
      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # --------------------------------------------------
      # Setup Python
      # --------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # --------------------------------------------------
      # Install Ansible + AWS dependencies
      # --------------------------------------------------
      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws

      # --------------------------------------------------
      # Ansible syntax check
      # --------------------------------------------------
      - name: Ansible syntax check
        run: |
          ansible-playbook playbook.yml --syntax-check

      # --------------------------------------------------
      # Dry-run on Pull Requests
      # --------------------------------------------------
      - name: Ansible dry-run (PR only)
        if: github.event_name == 'pull_request'
        run: |
          ansible-playbook playbook.yml \
            --check --diff

      # --------------------------------------------------
      # Deploy on merge to main
      # --------------------------------------------------
      - name: Ansible deploy (main branch)
        if: github.event_name == 'push'
        run: |
          ansible-playbook playbook.yml -vv
      
      # --------------------------------------------------
      # Deploy Cloudformation IAM glue template
      # --------------------------------------------------
      
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/glue-iam.yaml \
            --stack-name project-glue-iam-prod \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
